### ISSUE TITLE
Modules SushiIcon and useSushi nod found?

### ISSUE THREAD

**Issue by ThisBug** [sushiswap/sushiswap-frontend#1]

**Comment by acegilz** [comment]
same

**Comment by richaction** [comment]
same

**Comment by 1kxbt** [comment]
@chefnomi  Yes, two modules are missing

**Comment by liushooter** [comment]
same issue

**Comment by densmirnov** [comment]
Same here!

**Comment by liushooter** [comment]
Module not found: Can't resolve './contexts/SushiProvider' in 'frontend/src/App.tsx'

`import SushiProvider from './contexts/SushiProvider'`

**Comment by 1kxbt** [comment]
Chef's upload is missing his modified module, go to Twitter and tell him, let him know

**Comment by zoulinaini** [comment]
same

**Comment by luckywangming** [comment]
who can let him know

**Comment by HiZhaoYun** [comment]
he know, just don't want to upload it i guess!

**Comment by sangramsam** [comment]
same issue

**Comment by 1kxbt** [comment]
The chef has perfected the code and solved the problem

**Comment by richaction** [comment]
Can run !!

**Comment by ThisBug** [comment]
The chef solved the problem
