### ISSUE TITLE
Menu "about" link to  "410"

### ISSUE THREAD

**Issue by richaction** [sushiswap/sushiswap-frontend#6]
![image](https://user-images.githubusercontent.com/4279668/92600877-b31e7280-f2de-11ea-8256-91455e2ed732.png)
![image](https://user-images.githubusercontent.com/4279668/92600924-bfa2cb00-f2de-11ea-9bf5-ac93700b8453.png)

**Comment by 1kxbt** [comment]
There is a problem with the jump address, you can change it, It's not important

**Comment by richaction** [comment]
> There is a problem with the jump address, you can change it, It's not important

yes, and the offical website also fixed this address today.
